// templates/vue-vuex-bootstrap/src/views/HomePage.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col text-center">

        <h2>{{APP_NAME}}</h2>
        <p>We help you count easily, without errors.</p>


        <img class="landing-photo" src="/images/counter.jpg" alt="Counter" />
        <p class="counter-value">
          Counter: <strong>{{ counter }}</strong><br />
          <span v-if="lastAddition" style="font-size: 50%;">Last value added: {{ lastAddition }}</span>
        </p>
        <p>
          <button class="btn btn-primary" @click="addValue(1)">Increase by 1</button> &nbsp;
          <button class="btn btn-danger" @click="addValue(2)">Increase by 2</button>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
import { mapState, mapActions } from 'vuex';
export default {
  name: 'home',
  data: function() {
    return {
      APP_NAME: process.env.VUE_APP_NAME,
    }
  },

  computed: {
    ...mapState({
      counter: store => store.counter.counter,
      lastAddition: store => store.counter.lastAddition
    })
  },

  methods: {
    ...mapActions({
      addValue: 'addValue'
    })
  }
};
</script>

<style scoped>
  .landing-photo {
    width: 90%;
    max-width: 400px;

    margin-top: 20px;
    margin-bottom: 50px;
  }

  .counter-value {
    font-size: 2rem;
    margin: 30px 0;
  }
</style>

// templates/react-redux-bootstrap/src/routes/HomePage/index.js
import React from 'react';
import config from '../../config/default.json';

import { connect } from "react-redux";
import { addValue } from "../../store/counter.js";

import './styles.css';


class HomePage extends React.Component {

    addValue(value) {
        this.props.addValue(value);
    }

    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col text-center">

                        <h2>{config.APP_NAME}</h2>
                        <p>We help you count easily, without errors.</p>


                        <img className="landing-photo" src="/images/counter.jpg" alt="Counter" />
                        <p className="counter-value">
                            Counter: <strong>{this.props.counter}</strong><br />

                            {this.props.lastAddition
                                ? <span style={{ fontSize: '50%' }}>Last value added: { this.props.lastAddition }</span>
                                : ''}
                        </p>

                        <p>
                            <button className="btn btn-primary" onClick={() => { this.addValue(1); }}>Increase by 1</button> &nbsp;
                            <button className="btn btn-danger" onClick={() => { this.addValue(2); }}>Increase by 2</button>
                        </p>
                    </div>
                </div>
            </div>
        )
    }
}

function mapStateToProps(state) {
    return {
        counter: state.counter.counter,
        lastAddition: state.counter.lastAddition
    };
}

function mapDispatchToProps(dispatch) {
    return {
        addValue: (value) => { dispatch(addValue(value)); }
    };
}

export default connect(mapStateToProps, mapDispatchToProps)(HomePage);
